; generated by Component: ARM Compiler 5.06 update 7 (build 960) Tool: armcc [4d365d]
; commandline armcc [-S -olks32mc45x_trim.s --cpu=Cortex-M4 -I.\include .\lks32mc45x_trim.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

TRIM_Read PROC
        MRS      r2,PRIMASK
        CPSID    i
        LDR      r1,|L0.268|
        BIC      r0,r0,#3
        LDR      r3,[r1,#0x80]!
        ORR      r3,r3,#0x800
        STR      r3,[r1,#0]
        MOV      r3,#0x59000000
        STR      r3,[r1,#4]
        STR      r0,[r1,#4]
        LDR      r0,[r1,#0xc]
        MOV      r3,#0x95000000
        STR      r3,[r1,#4]
        LDR      r3,[r1,#0]
        BIC      r3,r3,#0x800
        STR      r3,[r1,#0]
        MSR      PRIMASK,r2
        BX       lr
        ENDP

TRIM_ReadUid PROC
        PUSH     {r4,lr}
        MRS      r3,PRIMASK
        CPSID    i
        LDR      r1,|L0.268|
        MOV      r2,#0x59000000
        STR      r2,[r1,#0x84]
        MOVS     r2,#0xc3
        STR      r2,[r1,#0xa8]
        LDR      r2,[r1,#0x80]
        ORR      r2,r2,#0x880
        STR      r2,[r1,#0x80]
        LDR      r2,|L0.272|
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.98|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.98|
        LDR      r2,|L0.272|
        STR      r4,[r0,#0]
        ADDS     r2,r2,#4
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.120|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.120|
        LDR      r2,|L0.272|
        STR      r4,[r0,#4]
        ADDS     r2,r2,#8
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.142|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.142|
        LDR      r2,|L0.272|
        STR      r4,[r0,#8]
        ADDS     r2,r2,#0xc
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.164|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.164|
        LDR      r2,|L0.276|
        STR      r4,[r0,#0xc]
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.184|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.184|
        LDR      r2,|L0.276|
        STR      r4,[r0,#0x10]
        SUBS     r2,r2,#0x10
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.206|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.206|
        LDR      r2,|L0.276|
        STR      r4,[r0,#0x14]
        SUBS     r2,r2,#0x20
        STR      r2,[r1,#0x84]
        LDR      r4,[r1,#0x8c]
|L0.228|
        LDR      r2,[r1,#0x98]
        LSLS     r2,r2,#23
        BPL      |L0.228|
        STR      r4,[r0,#0x18]
        LDR      r0,[r1,#0x80]!
        MOVS     r0,#0
        STR      r0,[r1,#0]
        LDR      r0,[r1,#0x28]
        BIC      r0,r0,#0xc3
        STR      r0,[r1,#0x28]
        MOV      r0,#0x95000000
        STR      r0,[r1,#4]
        MSR      PRIMASK,r3
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L0.268|
        DCD      0x4001a000
|L0.272|
        DCD      0x0003fc30
|L0.276|
        DCD      0x0003ff20

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 ".\\lks32mc45x_trim.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___17_lks32mc45x_trim_c_1f83b028____REV16|
#line 208 ".\\include\\cmsis_armcc.h"
|__asm___17_lks32mc45x_trim_c_1f83b028____REV16| PROC
#line 209

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___17_lks32mc45x_trim_c_1f83b028____REVSH|
#line 223
|__asm___17_lks32mc45x_trim_c_1f83b028____REVSH| PROC
#line 224

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___17_lks32mc45x_trim_c_1f83b028____RRX|
#line 410
|__asm___17_lks32mc45x_trim_c_1f83b028____RRX| PROC
#line 411

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT TRIM_Read [CODE]
        EXPORT TRIM_ReadUid [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
